"""added image

Revision ID: 239c3bed971a
Revises: 3d72aa6ca1a5
Create Date: 2025-11-04 15:57:39.079979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239c3bed971a'
down_revision = '3d72aa6ca1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.String(length=250), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('file')

    # ### end Alembic commands ###
